import{a as f,i as b,S as w}from"./assets/vendor-CjwUT-lV.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const y of s.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&o(y)}).observe(document,{childList:!0,subtree:!0});function a(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(t){if(t.ep)return;t.ep=!0;const s=a(t);fetch(t.href,s)}})();f.defaults.baseURL="https://pixabay.com/api/";const L="49355059-ef28fa3d6cd8d2c420ac797e4";async function h(r,e=1,a=15){const o={params:{key:L,q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:a}},t=(await f.get("",o)).data;try{return(!t.hits||t.hits.length===0)&&d("❌ Sorry, there are no images matching your search query. Please try again!"),t}catch{throw console.error("Error fetching data:",error),error}}function d(r){b.show({title:"",message:r,backgroundColor:"#FF5B61",titleColor:"white",messageColor:"white",position:"topRight"})}const p=document.querySelector(".gallery"),q={captions:!0,captionsData:"alt",captionDelay:250};let u=null;function g(r,e=!1){if(!r||r.length===0){p.innerHTML="";return}const a=r.map(o=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${o.largeImageURL}">
        <img
          class="gallery-image"
          src="${o.webformatURL}"
          alt="${o.tags}"
        />
      </a>
          <div class="image-info">
        <p class="image-info-text"><strong>Likes</strong> <span>${o.likes}</span></p>
        <p class="image-info-text"><strong>Views</strong> <span>${o.views}</span></p>
        <p class="image-info-text"><strong>Comments</strong> <span>${o.comments}</span></p>
        <p class="image-info-text"><strong>Downloads</strong> <span>${o.downloads}</span></p>
      </div>
    </li>
  `).join("");e?p.insertAdjacentHTML("beforeend",a):p.innerHTML=a,u?u.refresh():u=new w(".gallery a",q)}const S=document.getElementById("search-form"),l=document.querySelector(".loader"),n=document.querySelector(".load-more-button-js"),_=document.querySelector(".gallery");let i=1,x=15,c="";S.addEventListener("submit",T);n.addEventListener("click",m);async function T(r){try{if(r.preventDefault(),i=1,l.style.display="block",c=r.currentTarget.elements.query.value.trim(),!c){d("The request cant be empty, please fill in the input value!"),l.style.display="none";return}r.currentTarget.reset(),_.innerHTML="",n.style.display="none";const e=await h(c,i);l.style.display="none",g(e.hits),e.hits.length<15?n.style.display="none":n.style.display="inline-block",e.hits.length===0&&(n.style.display="none")}catch(e){console.error(e),d(e.response.data),l.style.display="none",n.style.display="none"}}async function m(r){try{i+=1,r.target.style.display="none",r.target.insertAdjacentElement("beforebegin",l),l.style.display="block";const e=await h(c,i),a=e.totalHits/x;if(l.style.display="none",i>=a)r.target.style.display="none",g(e.hits,!0),d("We're sorry, but you've reached the end of search results."),n.removeEventListener("click",m);else{r.target.style.display="inline-block",g(e.hits,!0);const s=document.querySelector(".gallery-item").getBoundingClientRect().height*2;window.scrollBy({top:s,behavior:"smooth"})}}catch(e){console.error(e)}}
//# sourceMappingURL=index.js.map
